#!/bin/bash
# jerry application server
# chkconfig: 345 20 80
# description: default daemon script for jerry
# processname: jerry

DAEMON="/usr/bin/jerry /opt/etc/jerry.xml


NAME=jerry
DESC="jerry application server"
PIDFILE=/var/$NAME.pid

# Source function library.
. /etc/rc.d/init.d/functions


case "$1" in
start)
    printf "%-50s" "Starting $NAME..."
    if [ -f $PIDFILE ]; then
        failure "datarunner appears to be already running (pid file exists)"
        exit 1
    fi
    PID=`$DAEMON > /var/jerry.log 2>&1 & echo $!`
    #echo "Saving PID" $PID " to " $PIDFILE
    if [ -z $PID ]; then
        printf "%s\n" "Fail"
    else
        echo $PID > $PIDFILE
        printf "%s\n" "Ok"
    fi
;;

status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;

stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
        if [ -f $PIDFILE ]; then
            # kill -HUP $PID
            kill $PID
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;
 
*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac
